#!/usr/bin/env python3
from __future__ import annotations

import sys


DEFAULT_IMAGE = "sub2api:ha-20260416b"


def main() -> None:
    image = sys.argv[1] if len(sys.argv) > 1 else DEFAULT_IMAGE
    lines = [
        "BIND_HOST=0.0.0.0",
        "SERVER_PORT=8080",
        "SERVER_MODE=release",
        "RUN_MODE=standard",
        "LOG_LEVEL=info",
        "LOG_FORMAT=json",
        "LOG_SERVICE_NAME=sub2api",
        "LOG_ENV=production",
        "LOG_CALLER=true",
        "LOG_STACKTRACE_LEVEL=error",
        "LOG_OUTPUT_TO_STDOUT=true",
        "LOG_OUTPUT_TO_FILE=true",
        "LOG_OUTPUT_FILE_PATH=",
        "LOG_ROTATION_MAX_SIZE_MB=100",
        "LOG_ROTATION_MAX_BACKUPS=10",
        "LOG_ROTATION_MAX_AGE_DAYS=7",
        "LOG_ROTATION_COMPRESS=true",
        "LOG_ROTATION_LOCAL_TIME=true",
        "LOG_SAMPLING_ENABLED=false",
        "LOG_SAMPLING_INITIAL=100",
        "LOG_SAMPLING_THEREAFTER=100",
        "SERVER_MAX_REQUEST_BODY_SIZE=268435456",
        "GATEWAY_MAX_BODY_SIZE=268435456",
        "SERVER_H2C_ENABLED=true",
        "SERVER_H2C_MAX_CONCURRENT_STREAMS=50",
        "SERVER_H2C_IDLE_TIMEOUT=75",
        "SERVER_H2C_MAX_READ_FRAME_SIZE=1048576",
        "SERVER_H2C_MAX_UPLOAD_BUFFER_PER_CONNECTION=2097152",
        "SERVER_H2C_MAX_UPLOAD_BUFFER_PER_STREAM=524288",
        "TZ=Asia/Shanghai",
        "",
        "# PostgreSQL service parameters (used on DB server)",
        "POSTGRES_USER=sub2api",
        "POSTGRES_PASSWORD=XIANjian4SANyun",
        "POSTGRES_DB=sub2api",
        "POSTGRES_MAX_CONNECTIONS=1024",
        "POSTGRES_SHARED_BUFFERS=1GB",
        "POSTGRES_EFFECTIVE_CACHE_SIZE=4GB",
        "POSTGRES_MAINTENANCE_WORK_MEM=128MB",
        "",
        "# External database connection parameters (used on business servers)",
        "DATABASE_HOST=pgproxy",
        "DATABASE_PORT=5432",
        "DATABASE_USER=sub2api",
        "DATABASE_PASSWORD=XIANjian4SANyun",
        "DATABASE_DBNAME=sub2api",
        "DATABASE_SSLMODE=disable",
        "DATABASE_MAX_OPEN_CONNS=256",
        "DATABASE_MAX_IDLE_CONNS=128",
        "DATABASE_CONN_MAX_LIFETIME_MINUTES=30",
        "DATABASE_CONN_MAX_IDLE_TIME_MINUTES=5",
        "",
        "# Redis service + external connection parameters",
        "REDIS_HOST=",
        "REDIS_PORT=6379",
        "REDIS_PASSWORD=XIANjian4SANyun",
        "REDIS_DB=0",
        "REDIS_MAXCLIENTS=50000",
        "REDIS_POOL_SIZE=4096",
        "REDIS_MIN_IDLE_CONNS=256",
        "REDIS_ENABLE_TLS=false",
        "",
        "ADMIN_EMAIL=727965481@qq.com",
        "ADMIN_PASSWORD=XIANjian4",
        "JWT_SECRET=e3032a99774855d59c8791d01c6686d2df29dfb5002b24ade52946ca07a8ded9",
        "JWT_EXPIRE_HOUR=24",
        "JWT_ACCESS_TOKEN_EXPIRE_MINUTES=0",
        "TOTP_ENCRYPTION_KEY=ae3ce3c0d89ec5b85b390b3d05b3bd6ea82bfd738fb14864f1c4ea97cdc1f41f",
        "",
        "SECURITY_URL_ALLOWLIST_ENABLED=false",
        "SECURITY_URL_ALLOWLIST_ALLOW_INSECURE_HTTP=true",
        "SECURITY_URL_ALLOWLIST_ALLOW_PRIVATE_HOSTS=true",
        "UPDATE_PROXY_URL=",
        "REDIS_SENTINEL_ENABLED=true",
        "REDIS_SENTINEL_MASTER_NAME=sub2api-redis",
        "REDIS_SENTINEL_ADDRS=10.77.0.1:26379,10.77.0.2:26379,10.77.0.3:26379,10.77.0.7:26379,10.77.0.8:26379",
        f"SUB2API_IMAGE={image}",
        "",
        "DATABASE_READER_HOST=pgproxy",
        "DATABASE_READER_PORT=5433",
        "DATABASE_READER_TARGET_SESSION_ATTRS=",
    ]
    print("\n".join(lines))


if __name__ == "__main__":
    main()
